server:
  port: ${PORT:8084}

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://rSharma:abc123@ec2-23-22-238-164.compute-1.amazonaws.com/bmc?authSource=admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}

ribbon:
  eureka:
    enabled: true