server:
  port: ${PORT:8083}

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://rSharma:abc123@ec2-23-22-238-164.compute-1.amazonaws.com/bmc?authSource=admin
#      host: ec2-54-204-240-140.compute-1.amazonaws.com
#      port: 27017
#      database: doctorservice
#      username: rSharma
#      password: abc123

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}

ribbon:
  eureka:
    enabled: true