server:
  port: ${PORT:8082}

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://rSharma:abc123@ec2-54-163-211-138.compute-1.amazonaws.com/userservice?authSource=admin
#      host: ec2-54-204-240-140.compute-1.amazonaws.com
#      port: 27017
#      database: doctorservice
#      username: rSharma
#      password: abc123

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

ribbon:
  eureka:
    enabled: true