server:
  port: ${PORT:8081}

spring:
  application:
    name: doctor-service
  data:
    mongodb:
      uri: mongodb://rSharma:abc123@ec2-52-90-149-155.compute-1.amazonaws.com/doctorservice?authSource=admin
#      host: ec2-54-204-240-140.compute-1.amazonaws.com
#      port: 27017
#      database: doctorservice
#      username: rSharma
#      password: abc123

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

ribbon:
  eureka:
    enabled: true