server:
  port: ${PORT:8082}

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://sweet-home.crojtkyz2wlp.us-east-1.rds.amazonaws.com:3306/booking
    username: admin
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: mongodb://rSharma:abc123@ec2-23-22-238-164.compute-1.amazonaws.com/bmc?authSource=admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST_NAME:localhost}:8761/eureka/
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}

ribbon:
  eureka:
    enabled: true